### ISSUE TITLE
Incorrect templating in Server config

### ISSUE THREAD

**Issue by morgante** [forseti-security/terraform-google-forseti#193]
The server config has some variables which don't get properly templated.

Ex.

```
        - resource: groups_settings_violations
          should_notify: true
          notifiers:
            
            # Upload violations to GCS.
            - name: gcs_violations
              configuration:
                data_format: csv
                # gcs_path should begin with "gs://"
                gcs_path: gs://{FORSETI_BUCKET}/scanner_violations
```
