### ISSUE TITLE
Enable configuration of gcs_violations output file format

### ISSUE THREAD

**Issue by potsec** [forseti-security/terraform-google-forseti#409]
Currently the terraform template defines 
```
            - name: gcs_violations
              configuration:
                data_format: csv
                # gcs_path should begin with "gs://"
                gcs_path: gs://${FORSETI_BUCKET}/scanner_violations
```
We use json format output files, so it would be useful if the output was configurable in the Terraform template (`forseti_conf_server.yaml.tpl`) via an input variable, such as `gcs_violations_file_format = json`.
```
            - name: gcs_violations
              configuration:
                data_format: ${GCS_VIOLATIONS_FILE_FORMAT}
                # gcs_path should begin with "gs://"
                gcs_path: gs://${FORSETI_BUCKET}/scanner_violations
```
